import { Poppins } from "next/font/google";
import "./globals.css";
import { cn } from "@/utils/utils";

const poppins = Poppins({ subsets: ["latin"], weight: [ "400", "500", "600", "700" ] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn("w-screen overflow-x-hidden", poppins.className)}>{children}</body>
    </html>
  );
}
