export const catagories = [
    'medicine',
    'surgical',
    'syrup',
    'medicine',
    'surgical',
    'syrup',
    'medicine',
    'surgical',
    'syrup',
    'medicine',
    'surgical',
    'syrup',
    'medicine',
    'surgical',
    'syrup',
    'medicine',
    'surgical',
    'syrup',
    'medicine',
    'surgical',
    'syrup',
]

export const products = [
    {
        _id: 1,
        name: "A-Cal D",
        menufacturer: "Aci Limited",
        catagory: 'medicine',
        oldPrice: 212,
        newPrice: 168,
    },
    {
        _id: 2,
        name: "A-Cal D",
        menufacturer: "Aci Limited",
        catagory: 'medicine',
        oldPrice: 212,
        newPrice: 168,
    },
    {
        _id: 3,
        name: "A-Cal D",
        menufacturer: "Aci Limited",
        catagory: 'medicine',
        oldPrice: 212,
        newPrice: 168,
    },
    {
        _id: 4,
        name: "A-Cal D",
        menufacturer: "Aci Limited",
        catagory: 'medicine',
        oldPrice: 212,
        newPrice: 168,
    },
    {
        _id: 5,
        name: "A-Cal D",
        menufacturer: "Aci Limited",
        catagory: 'medicine',
        oldPrice: 212,
        newPrice: 168,
    },
    {
        _id: 6,
        name: "A-Cal D",
        menufacturer: "Aci Limited",
        catagory: 'medicine',
        oldPrice: 212,
        newPrice: 168,
    },
    {
        _id: 7,
        name: "A-Cal D",
        menufacturer: "Aci Limited",
        catagory: 'medicine',
        oldPrice: 212,
        newPrice: 168,
    },
    {
        _id: 8,
        name: "A-Cal D",
        menufacturer: "Aci Limited",
        catagory: 'medicine',
        oldPrice: 212,
        newPrice: 168,
    },
    {
        _id: 9,
        name: "A-Cal D",
        menufacturer: "Aci Limited",
        catagory: 'medicine',
        oldPrice: 212,
        newPrice: 168,
    },
    {
        _id: 10,
        name: "A-Cal D",
        menufacturer: "Aci Limited",
        catagory: 'medicine',
        oldPrice: 212,
        newPrice: 168,
    },
    {
        _id: 11,
        name: "A-Cal D",
        menufacturer: "Aci Limited",
        catagory: 'medicine',
        oldPrice: 212,
        newPrice: 168,
    },
    {
        _id: 12,
        name: "A-Cal D",
        menufacturer: "Aci Limited",
        catagory: 'medicine',
        oldPrice: 212,
        newPrice: 168,
    },
]